version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
    container_name: app
    command: npm start

  redis:
    image: redis:6.0.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
